version: '3'
services:
  app:
    build: ./app
    ports:
      - "6000:13000"
    volumes:
      - appvol:/vol
    env_file:
      - .env
    command: ["/app/bin/start-supervisor"]
volumes:
  appvol: {}
